# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- script: php -v
  displayName: 'Check PHP version'

- script: |
    echo "Running PHP script test"
    php -r 'echo "Hello Facebook from PHP!";'
  displayName: 'Test PHP script'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)'
    artifactName: 'drop'
